[tool.poetry]
name = "camp-kitchen-planner"
version = "0.1.0"
description = ""
authors = ["Antoine Gallix <antoine.gallix@a2ei.org>"]
readme = "README.md"
packages = [{include = "camp_kitchen_planner"}]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
